repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
        args: ["--assume-in-merge"]
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
